/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('restaurants').del()
  await knex('restaurants').insert([
    {
      id: 1, 
      restaurant_name: "Wendy's",
      address: '19 Western Battery Rd, Toronto, ON M6K 3S4',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://order.wendys.com/',
    },
    {
      id: 2, 
      restaurant_name: "McDonald's",
      address: '25 Joe Shuster Way, Toronto, ON M6K 0C7',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://www.mcdonalds.com/',
    },    
    {
      id: 3, 
      restaurant_name: "Kibo Sushi House - Liberty",
      address: '171 E Liberty St #146, Toronto, ON M6K 3P6',
      cuisine: 'Japanese',
      price_level: '$',
      website: 'https://kibosushi.com/',
    },    
    {
      id: 4, 
      restaurant_name: "Maurya East Indian Roti",
      address: '150 E Liberty St, Toronto, ON M6K 3R5',
      cuisine: 'Indian',
      price_level: '$$',
      website: 'https://www.mauryaindianrestaurants.com/locations/liberty/menu/',
    },    
    {
      id: 5, 
      restaurant_name: "LOCAL Public Eatery",
      address: '171 E Liberty St #100, Toronto, ON M6K 3P6',
      cuisine: 'Canadian pub',
      price_level: '$$',
      website: 'https://localpubliceatery.com/neighbourhoods/liberty-village/menu/',
    },    
    {
      id: 6, 
      restaurant_name: "Chiang Mai",
      address: '171 E Liberty St Unit 144, Toronto, ON M6K 3P6',
      cuisine: 'Thai',
      price_level: '$$',
      website: 'https://www.chiangmai.ca/',
    },    
    {
      id: 7, 
      restaurant_name: "Roses Social",
      address: "111 Princes' Blvd 2nd floor, Toronto, ON M6K 3C3",
      cuisine: 'North American bistro',
      price_level: '$$$',
      website: 'https://rosessocial.ca/menu',
    },    
    {
      id: 8, 
      restaurant_name: "The Craft",
      address: '107 Atlantic Ave, Toronto, ON M6K 1Y2',
      cuisine: 'Bar & grill',
      price_level: '$$$',
      website: 'https://thecraftbrasserie.com/',
    },    
    {
      id: 9, 
      restaurant_name: "NODO Liberty",
      address: '120 Lynn Williams St, Toronto, ON M6K 3N6',
      cuisine: 'Italian',
      price_level: '$$$',
      website: 'https://www.nodorestaurant.ca/',
    },
    {
      id: 10, 
      restaurant_name: "Tim Hortons",
      address: '45 Manitoba Dr, Toronto, ON M6K 3C3',
      cuisine: 'Canadian café',
      price_level: '$',
      website: 'https://www.timhortons.ca/',
    },
    {
      id: 11, 
      restaurant_name: "Thai Express",
      address: '218 Yonge St, Toronto, ON M5B 2H6',
      cuisine: 'Thai',
      price_level: '$',
      website: 'https://thaiexpress.ca/menu/',
    },
    {
      id: 12, 
      restaurant_name: "Mr. Souvlaki",
      address: '200 Front St W, Toronto, ON M5V 3K2',
      cuisine: 'Greek',
      price_level: '$',
      website: 'https://mrsouvlaki.ca/store/simcoe-place/',
    },
    {
      id: 13, 
      restaurant_name: "A&W",
      address: '60 John St, Toronto, ON M5V 3W2',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://web.aw.ca/en/our-menu',
    },
    {
      id: 14, 
      restaurant_name: "Korean Grill House",
      address: '214 Queen St W, Toronto, ON M5V 1Z2',
      cuisine: 'Korean',
      price_level: '$$',
      website: 'https://koreangrillhouse.com/our-menus/',
    },
    {
      id: 15, 
      restaurant_name: "Cafe Landwer",
      address: '165 University Ave, Toronto, ON M5H 3B8',
      cuisine: 'Mediterranean',
      price_level: '$$',
      website: 'https://www.landwer.ca/our-menus/',
    },
    {
      id: 16, 
      restaurant_name: "Pizzeria Libretto",
      address: '155 University Ave, Toronto, ON M5H 3B7',
      cuisine: 'Italian',
      price_level: '$$',
      website: 'https://www.pizzerialibretto.com/menus/',
    },
    {
      id: 17, 
      restaurant_name: "Richmond Station",
      address: '1 Richmond St W, Toronto, ON M5H 3W4',
      cuisine: 'Canadian',
      price_level: '$$$',
      website: 'https://richmondstation.ca/menu/',
    },
    {
      id: 18, 
      restaurant_name: "Leña Restaurante",
      address: '176 Yonge St, Toronto, ON M5C 2L7',
      cuisine: 'Latin American',
      price_level: '$$$',
      website: 'https://www.lenarestaurante.com/#menus',
    },
    {
      id: 19, 
      restaurant_name: "Volos Greek Cuisine",
      address: '133 Richmond St W, Toronto, ON M5H 2L3',
      cuisine: 'Greek',
      price_level: '$$$',
      website: 'https://www.volos.ca/menu',
    },
    {
      id: 20, 
      restaurant_name: "McDonald's",
      address: '260 Yonge St Unit J-002, Toronto, ON M5B 2L9',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://www.mcdonalds.com/',
    },
    {
      id: 21, 
      restaurant_name: "Imperial Pub",
      address: '54 Dundas St E, Toronto, ON M5B 1C7',
      cuisine: 'Canadian pub',
      price_level: '$',
      website: 'https://imperialpub.com/menu',
    },
    {
      id: 22, 
      restaurant_name: "Salad King",
      address: '340 Yonge St, Toronto, ON M5B 1R8',
      cuisine: 'Thai',
      price_level: '$',
      website: 'https://saladking.com/#menu-block',
    },
    {
      id: 23, 
      restaurant_name: "Fran's Restaurant",
      address: '200 Victoria St, Toronto, ON M5B 2R3',
      cuisine: 'Canadian Diner',
      price_level: '$$',
      website: 'https://www.fransrestaurant.com/',
    },
    {
      id: 24, 
      restaurant_name: "Firkin on Yonge",
      address: '207 Yonge St, Toronto, ON M5B 2H1',
      cuisine: 'British pub',
      price_level: '$$',
      website: 'https://www.firkinpubs.com/firkinonyonge/',
    },
    {
      id: 25, 
      restaurant_name: "Trattoria Mercatto",
      address: '220 Yonge St, Toronto, ON M5B 2H1',
      cuisine: 'Italian',
      price_level: '$$',
      website: 'https://trattoria.mercatto.ca/',
    },
    {
      id: 26, 
      restaurant_name: "Jump Restaurant",
      address: '18 Wellington St W, Toronto, ON M5L 1G4',
      cuisine: 'North American with Italian influences',
      price_level: '$$$',
      website: 'https://www.jumprestaurant.com/#menus',
    },
    {
      id: 27, 
      restaurant_name: "Bellissimo Pizzeria & Ristorante",
      address: '164 The Esplanade, Toronto, ON M5A 4H2',
      cuisine: 'Italian',
      price_level: '$',
      website: 'https://bellissimopizzeriaristorante.ca/menu',
    },
    {
      id: 28, 
      restaurant_name: "McDonald's",
      address: '121 Front St E, Toronto, ON M5A 4P7',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://www.mcdonalds.com/',
    },
    {
      id: 29, 
      restaurant_name: "A&W",
      address: '85 Front St E, Toronto, ON M5E 1B8',
      cuisine: 'Fast-food burger chain',
      price_level: '$',
      website: 'https://web.aw.ca/en/our-menu',
    },
    {
      id: 30, 
      restaurant_name: "HOTHOUSE",
      address: '35 Church St, Toronto, ON M5E 1T3',
      cuisine: 'Canadian',
      price_level: '$$',
      website: 'https://www.hothouserestaurant.com/menu/',
    },
    {
      id: 31, 
      restaurant_name: "C'est What",
      address: '67 Front St E, Toronto, ON M5E 1B5',
      cuisine: 'Canadian pub',
      price_level: '$$',
      website: 'https://cestwhat.com/fooddrink',
    },
    {
      id: 32, 
      restaurant_name: "The Old Spaghetti Factory",
      address: '54 The Esplanade, Toronto, ON M5E 1A6',
      cuisine: 'Italian',
      price_level: '$$',
      website: 'https://oldspaghettifactory.ca/locations/toronto/',
    },
    {
      id: 33, 
      restaurant_name: "The Keg Steakhouse + Bar",
      address: '26 The Esplanade, Toronto, ON M5E 1A7',
      cuisine: 'Canadian steakhouse',
      price_level: '$$$',
      website: 'https://www.thekeg.com/en/locations/esplanade',
    },
    {
      id: 34, 
      restaurant_name: "The Sultan's Tent and Cafe Moroc",
      address: '49 Front St E, Toronto, ON M5E 1B3',
      cuisine: 'Middle Eastern',
      price_level: '$$$',
      website: 'https://www.thesultanstent.com/',
    },
    {
      id: 35, 
      restaurant_name: "Chipotle Mexican Grill",
      address: '123 Front St W, Toronto, ON M5J 2M2',
      cuisine: 'Mexican',
      price_level: '$',
      website: 'https://chipotle.com/#menu',
    },
    {
      id: 36, 
      restaurant_name: "La Carnita",
      address: '106 John St, Toronto, ON M5H 1X9',
      cuisine: 'Mexican',
      price_level: '$$',
      website: 'https://www.lacarnita.com/',
    },
    {
      id: 37, 
      restaurant_name: "PAI",
      address: '18 Duncan St, Toronto, ON M5H 3G8',
      cuisine: 'Thai',
      price_level: '$$',
      website: 'https://www.paitoronto.com/',
    },
    {
      id: 38, 
      restaurant_name: "Hey Lucy",
      address: '295 King St W, Toronto, ON M5V 1J5',
      cuisine: 'Italian',
      price_level: '$$',
      website: 'https://heylucy.ca/menu/',
    },
    {
      id: 39, 
      restaurant_name: "Luma",
      address: '350 King Street West, Toronto, ON M5V 3X5',
      cuisine: 'International',
      price_level: '$$$',
      website: 'https://www.lumarestaurant.com/#menus',
    },
    {
      id: 40, 
      restaurant_name: "Byblos Downtown",
      address: '11 Duncan St, Toronto, ON M5V 3M2',
      cuisine: 'Middle Eastern',
      price_level: '$$$',
      website: 'https://byblosdowntown.com/#menu',
    },
    {
      id: 41, 
      restaurant_name: "The Shore Club",
      address: '155 Wellington St W, Toronto, ON M5V 3H1',
      cuisine: 'Canadian steakhouse',
      price_level: '$$$',
      website: 'https://theshoreclub.ca/toronto/menus/',
    },
    {
      id: 42, 
      restaurant_name: "Pizza Nova",
      address: '365 Front St W, Toronto, ON M5V 3S8',
      cuisine: 'Italian',
      price_level: '$',
      website: 'https://weborders.pizzanova.com/PNAPI/order/menu/',
    },
    {
      id: 43, 
      restaurant_name: "Tim Hortons",
      address: '120 Fort York Blvd, Toronto, ON M5V 0E3',
      cuisine: 'Canadian café',
      price_level: '$',
      website: 'https://www.timhortons.ca/',
    },
    {
      id: 44, 
      restaurant_name: "St. Louis Bar & Grill",
      address: '313 Bremner Blvd, Toronto, ON M5V 3V3',
      cuisine: 'American',
      price_level: '$$',
      website: 'https://www.stlouiswings.com/stlouis-menu/',
    },
    {
      id: 45, 
      restaurant_name: "Annalakshmi Toronto",
      address: '277 Wellington St W Unit 100b, Toronto, ON M5V 3E4',
      cuisine: 'South Indian',
      price_level: '$$',
      website: 'https://annalakshmi.ca/toronto-menu/',
    },
    {
      id: 46, 
      restaurant_name: "The Rec Room",
      address: '255 Bremner Blvd, Toronto, ON M5V 3M9',
      cuisine: 'Canadian',
      price_level: '$$',
      website: 'https://www.therecroom.com/toronto-roundhouse/restaurant/three10',
    },
    {
      id: 47, 
      restaurant_name: "e11even",
      address: '15 York Street, Toronto, ON M5J 0A3',
      cuisine: 'American',
      price_level: '$$$',
      website: 'https://www.e11even.ca/menu',
    },
    {
      id: 48, 
      restaurant_name: "Aria",
      address: '25 York St, Toronto, ON M5J 2V5',
      cuisine: 'Italian',
      price_level: '$$$',
      website: 'https://ariaristorante.ca/',
    },
    {
      id: 49, 
      restaurant_name: "Pizza Pizza",
      address: 'The PATH - Union Station, Toronto, ON M5J 1E5',
      cuisine: 'Italian',
      price_level: '$',
      website: 'https://www.pizzapizza.ca/',
    },
    {
      id: 50, 
      restaurant_name: "Jack Astor's Bar & Grill",
      address: '144 Front St W, Toronto, ON M5J 2L7',
      cuisine: 'North American',
      price_level: '$$',
      website: 'https://jackastors.com/menu/',
    },
    {
      id: 51, 
      restaurant_name: "Real Sports",
      address: '15 York St, Toronto, ON M5J 2Z2',
      cuisine: 'Canadian pub',
      price_level: '$$',
      website: 'https://www.rs.ca/menu-dinner',
    },
    {
      id: 52, 
      restaurant_name: "La Bettola Di Terroni",
      address: '106 Victoria St, Toronto, ON M5C 2B4',
      cuisine: 'Italian',
      price_level: '$$$',
      website: 'https://www.terroni.com/locations/la-bettola-di-terroni',
    },
  ]);
};
