/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('restos_venues').del()
  await knex('restos_venues').insert([
    {
      id: 1, 
      resto_id: 1,
      venue_id: 1,
      price_level: '$',
      distance_venue: 1200,
      duration_venue: 17,
    },
    {
      id: 2, 
      resto_id: 2,
      venue_id: 1,
      price_level: '$',
      distance_venue: 1000,
      duration_venue: 14,
    },    
    {
      id: 3, 
      resto_id: 3,
      venue_id: 1,
      price_level: '$',
      distance_venue: 700,
      duration_venue: 10,
    },    
    {
      id: 4, 
      resto_id: 4,
      venue_id: 1,
      price_level: '$$',
      distance_venue: 900,
      duration_venue: 12,
    },    
    {
      id: 5, 
      resto_id: 5,
      venue_id: 1,
      price_level: '$$',
      distance_venue: 650,
      duration_venue: 9,
    },    
    {
      id: 6, 
      resto_id: 6,
      venue_id: 1,
      price_level: '$$',
      distance_venue: 700,
      duration_venue: 9,
    },    
    {
      id: 7, 
      resto_id: 7,
      venue_id: 1,
      price_level: '$$$',
      distance_venue: 550,
      duration_venue: 7,
    },    
    {
      id: 8, 
      resto_id: 8,
      venue_id: 1,
      price_level: '$$$',
      distance_venue: 650,
      duration_venue: 9,
    },    
    {
      id: 9, 
      resto_id: 9,
      venue_id: 1,
      price_level: '$$$',
      distance_venue: 900,
      duration_venue: 13,
    },
    {
      id: 10, 
      resto_id: 1,
      venue_id: 2,
      price_level: '$',
      distance_venue: 1600,
      duration_venue: 23,
    },
    {
      id: 11, 
      resto_id: 10,
      venue_id: 2,
      price_level: '$',
      distance_venue: 900,
      duration_venue: 13,
    },
    {
      id: 12, 
      resto_id: 3,
      venue_id: 2,
      price_level: '$',
      distance_venue: 1500,
      duration_venue: 21,
    },
    {
      id: 13, 
      resto_id: 4,
      venue_id: 2,
      price_level: '$$',
      distance_venue: 1600,
      duration_venue: 22,
    },
    {
      id: 14, 
      resto_id: 5,
      venue_id: 2,
      price_level: '$$',
      distance_venue: 1400,
      duration_venue: 20,
    },
    {
      id: 15, 
      resto_id: 6,
      venue_id: 2,
      price_level: '$$',
      distance_venue: 1500,
      duration_venue: 21,
    },
    {
      id: 16, 
      resto_id: 7,
      venue_id: 2,
      price_level: '$$$',
      distance_venue: 700,
      duration_venue: 10,
    },
    {
      id: 17, 
      resto_id: 8,
      venue_id: 2,
      price_level: '$$$',
      distance_venue: 1400,
      duration_venue: 21,
    },
    {
      id: 18, 
      resto_id: 9,
      venue_id: 2,
      price_level: '$$$',
      distance_venue: 1600,
      duration_venue: 23,
    },
    {
      id: 19, 
      resto_id: 11,
      venue_id: 3,
      price_level: '$',
      distance_venue: 750,
      duration_venue: 10,
    },
    {
      id: 20, 
      resto_id: 12,
      venue_id: 3,
      price_level: '$',
      distance_venue: 650,
      duration_venue: 9,
    },
    {
      id: 21, 
      resto_id: 13,
      venue_id: 3,
      price_level: '$',
      distance_venue: 800,
      duration_venue: 12,
    },
    {
      id: 22, 
      resto_id: 14,
      venue_id: 3,
      price_level: '$$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 23, 
      resto_id: 15,
      venue_id: 3,
      price_level: '$$',
      distance_venue: 200,
      duration_venue: 3,
    },
    {
      id: 24, 
      resto_id: 16,
      venue_id: 3,
      price_level: '$$',
      distance_venue: 250,
      duration_venue: 4,
    },
    {
      id: 25, 
      resto_id: 17,
      venue_id: 3,
      price_level: '$$$',
      distance_venue: 500,
      duration_venue: 7,
    },
    {
      id: 26, 
      resto_id: 18,
      venue_id: 3,
      price_level: '$$$',
      distance_venue: 700,
      duration_venue: 9,
    },
    {
      id: 27, 
      resto_id: 19,
      venue_id: 3,
      price_level: '$$$',
      distance_venue: 56,
      duration_venue: 1,
    },
    {
      id: 28, 
      resto_id: 20,
      venue_id: 4,
      price_level: '$',
      distance_venue: 350,
      duration_venue: 6,
    },
    {
      id: 29, 
      resto_id: 21,
      venue_id: 4,
      price_level: '$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 30, 
      resto_id: 22,
      venue_id: 4,
      price_level: '$',
      distance_venue: 550,
      duration_venue: 8,
    },
    {
      id: 31, 
      resto_id: 23,
      venue_id: 4,
      price_level: '$$',
      distance_venue: 41,
      duration_venue: 1,
    },
    {
      id: 32, 
      resto_id: 24,
      venue_id: 4,
      price_level: '$$',
      distance_venue: 130,
      duration_venue: 2,
    },
    {
      id: 33, 
      resto_id: 25,
      venue_id: 4,
      price_level: '$$',
      distance_venue: 290,
      duration_venue: 4,
    },
    {
      id: 34, 
      resto_id: 18,
      venue_id: 4,
      price_level: '$$$',
      distance_venue: 500,
      duration_venue: 7,
    },
    {
      id: 35, 
      resto_id: 17,
      venue_id: 4,
      price_level: '$$$',
      distance_venue: 400,
      duration_venue: 6,
    },
    {
      id: 36, 
      resto_id: 26,
      venue_id: 4,
      price_level: '$$$',
      distance_venue: 750,
      duration_venue: 11,
    },
    {
      id: 37, 
      resto_id: 27,
      venue_id: 5,
      price_level: '$',
      distance_venue: 850,
      duration_venue: 12,
    },
    {
      id: 38, 
      resto_id: 28,
      venue_id: 5,
      price_level: '$',
      distance_venue: 600,
      duration_venue: 9,
    },
    {
      id: 39, 
      resto_id: 29,
      venue_id: 5,
      price_level: '$',
      distance_venue: 450,
      duration_venue: 6,
    },
    {
      id: 40, 
      resto_id: 30,
      venue_id: 5,
      price_level: '$$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 41, 
      resto_id: 31,
      venue_id: 5,
      price_level: '$$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 42, 
      resto_id: 32,
      venue_id: 5,
      price_level: '$$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 43, 
      resto_id: 33,
      venue_id: 5,
      price_level: '$$$',
      distance_venue: 300,
      duration_venue: 4,
    },
    {
      id: 44, 
      resto_id: 34,
      venue_id: 5,
      price_level: '$$$',
      distance_venue: 250,
      duration_venue: 4,
    },
    {
      id: 45, 
      resto_id: 26,
      venue_id: 5,
      price_level: '$$$',
      distance_venue: 400,
      duration_venue: 6,
    },
    {
      id: 46, 
      resto_id: 35,
      venue_id: 6,
      price_level: '$',
      distance_venue: 700,
      duration_venue: 9,
    },
    {
      id: 47, 
      resto_id: 12,
      venue_id: 6,
      price_level: '$',
      distance_venue: 500,
      duration_venue: 7,
    },
    {
      id: 48, 
      resto_id: 13,
      venue_id: 6,
      price_level: '$',
      distance_venue: 150,
      duration_venue: 2,
    },
    {
      id: 49, 
      resto_id: 36,
      venue_id: 6,
      price_level: '$$',
      distance_venue: 120,
      duration_venue: 2,
    },
    {
      id: 50, 
      resto_id: 37,
      venue_id: 6,
      price_level: '$$',
      distance_venue: 200,
      duration_venue: 3,
    },
    {
      id: 51, 
      resto_id: 38,
      venue_id: 6,
      price_level: '$$',
      distance_venue: 91,
      duration_venue: 1,
    },
    {
      id: 52, 
      resto_id: 39,
      venue_id: 6,
      price_level: '$$$',
      distance_venue: 88,
      duration_venue: 1,
    },
    {
      id: 53, 
      resto_id: 40,
      venue_id: 6,
      price_level: '$$$',
      distance_venue: 140,
      duration_venue: 2,
    },
    {
      id: 54, 
      resto_id: 41,
      venue_id: 6,
      price_level: '$$$',
      distance_venue: 400,
      duration_venue: 6,
    },
    {
      id: 55, 
      resto_id: 42,
      venue_id: 7,
      price_level: '$',
      distance_venue: 230,
      duration_venue: 3,
    },
    {
      id: 56, 
      resto_id: 43,
      venue_id: 7,
      price_level: '$',
      distance_venue: 750,
      duration_venue: 10,
    },
    {
      id: 57, 
      resto_id: 13,
      venue_id: 7,
      price_level: '$',
      distance_venue: 500,
      duration_venue: 7,
    },
    {
      id: 58, 
      resto_id: 44,
      venue_id: 7,
      price_level: '$$',
      distance_venue: 140,
      duration_venue: 2,
    },
    {
      id: 59, 
      resto_id: 45,
      venue_id: 7,
      price_level: '$$',
      distance_venue: 290,
      duration_venue: 4,
    },
    {
      id: 60, 
      resto_id: 46,
      venue_id: 7,
      price_level: '$$',
      distance_venue: 170,
      duration_venue: 3,
    },
    {
      id: 61, 
      resto_id: 41,
      venue_id: 7,
      price_level: '$$$',
      distance_venue: 700,
      duration_venue: 10,
    },
    {
      id: 62, 
      resto_id: 47,
      venue_id: 7,
      price_level: '$$$',
      distance_venue: 600,
      duration_venue: 8,
    },
    {
      id: 63, 
      resto_id: 48,
      venue_id: 7,
      price_level: '$$$',
      distance_venue: 650,
      duration_venue: 9,
    },
    {
      id: 64, 
      resto_id: 35,
      venue_id: 8,
      price_level: '$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 65, 
      resto_id: 12,
      venue_id: 8,
      price_level: '$',
      distance_venue: 140,
      duration_venue: 2,
    },
    {
      id: 66, 
      resto_id: 13,
      venue_id: 8,
      price_level: '$',
      distance_venue: 300,
      duration_venue: 4,
    },
    {
      id: 67, 
      resto_id: 36,
      venue_id: 8,
      price_level: '$$',
      distance_venue: 290,
      duration_venue: 4,
    },
    {
      id: 68, 
      resto_id: 37,
      venue_id: 8,
      price_level: '$$',
      distance_venue: 350,
      duration_venue: 5,
    },
    {
      id: 69, 
      resto_id: 38,
      venue_id: 8,
      price_level: '$$',
      distance_venue: 270,
      duration_venue: 4,
    },
    {
      id: 70, 
      resto_id: 39,
      venue_id: 8,
      price_level: '$$$',
      distance_venue: 260,
      duration_venue: 4,
    },
    {
      id: 71, 
      resto_id: 40,
      venue_id: 8,
      price_level: '$$$',
      distance_venue: 300,
      duration_venue: 4,
    },
    {
      id: 72, 
      resto_id: 41,
      venue_id: 8,
      price_level: '$$$',
      distance_venue: 34,
      duration_venue: 1,
    },
    {
      id: 73, 
      resto_id: 49,
      venue_id: 9,
      price_level: '$',
      distance_venue: 600,
      duration_venue: 8,
    },
    {
      id: 74, 
      resto_id: 35,
      venue_id: 9,
      price_level: '$',
      distance_venue: 450,
      duration_venue: 6,
    },
    {
      id: 75, 
      resto_id: 12,
      venue_id: 9,
      price_level: '$',
      distance_venue: 650,
      duration_venue: 9,
    },
    {
      id: 76, 
      resto_id: 50,
      venue_id: 9,
      price_level: '$$',
      distance_venue: 550,
      duration_venue: 8,
    },
    {
      id: 77, 
      resto_id: 51,
      venue_id: 9,
      price_level: '$$',
      distance_venue: 150,
      duration_venue: 2,
    },
    {
      id: 78, 
      resto_id: 46,
      venue_id: 9,
      price_level: '$$',
      distance_venue: 600,
      duration_venue: 9,
    },
    {
      id: 79, 
      resto_id: 47,
      venue_id: 9,
      price_level: '$$$',
      distance_venue: 130,
      duration_venue: 2,
    },
    {
      id: 80, 
      resto_id: 48,
      venue_id: 9,
      price_level: '$$$',
      distance_venue: 18,
      duration_venue: 1,
    },
    {
      id: 81, 
      resto_id: 48,
      venue_id: 9,
      price_level: '$$$',
      distance_venue: 850,
      duration_venue: 12,
    },
    {
      id: 82, 
      resto_id: 20,
      venue_id: 10,
      price_level: '$',
      distance_venue: 350,
      duration_venue: 6,
    },
    {
      id: 83, 
      resto_id: 21,
      venue_id: 10,
      price_level: '$',
      distance_venue: 550,
      duration_venue: 8,
    },
    {
      id: 84, 
      resto_id: 22,
      venue_id: 10,
      price_level: '$',
      distance_venue: 550,
      duration_venue: 8,
    },
    {
      id: 85, 
      resto_id: 23,
      venue_id: 10,
      price_level: '$$',
      distance_venue: 210,
      duration_venue: 3,
    },
    {
      id: 86, 
      resto_id: 24,
      venue_id: 10,
      price_level: '$$',
      distance_venue: 230,
      duration_venue: 3,
    },
    {
      id: 87, 
      resto_id: 25,
      venue_id: 10,
      price_level: '$$',
      distance_venue: 290,
      duration_venue: 4,
    },
    {
      id: 88, 
      resto_id: 18,
      venue_id: 10,
      price_level: '$$$',
      distance_venue: 120,
      duration_venue: 2,
    },
    {
      id: 89, 
      resto_id: 17,
      venue_id: 10,
      price_level: '$$$',
      distance_venue: 200,
      duration_venue: 3,
    },
    {
      id: 90, 
      resto_id: 52,
      venue_id: 10,
      price_level: '$$$',
      distance_venue: 220,
      duration_venue: 3,
    },
  ]);
};
